dist:     trusty
sudo:     required

language: cpp

os:
  - linux

before_install:
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -y libc++-dev libboost-dev libboost-system-dev valgrind doxygen

compiler:
  - g++
  - clang++ 

env:
  - BUILD_TYPE=Debug STANDARD=11
  - BUILD_TYPE=Release STANDARD=11
  - BUILD_TYPE=Debug STANDARD=14
  - BUILD_TYPE=Release STANDARD=14

matrix:
  exclude:
  - compiler: g++
    env: BUILD_TYPE=Debug STANDARD=14
  - compiler: g++
    env: BUILD_TYPE=Release STANDARD=14
  
script:
    - mkdir build
    - cd build
    - echo "CMAKE_CXX_STANDARD=     $STANDARD"
    - cmake .. -DBUILD_TESTING=ON -DPARANOID_WARNING=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=$STANDARD -DCMAKE_RULE_MESSAGES:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCLANG_LIBPP="-stdlib=libc++"
    - cmake --build .
    - ctest --output-on-failure
