if(DEFINED ENV{ENABLE_STAT} )
  option(WFC_ENABLE_STAT "Enable statistics components" $ENV{ENABLE_STAT})
elseif(DEFINED ENABLE_STAT)
  option(WFC_ENABLE_STAT "Enable statistics components" ${ENABLE_STAT})
else()
  option(WFC_ENABLE_STAT "Enable statistics components" OFF)
endif()
message(STATUS "Enable WFC statistics components ${WFC_ENABLE_STAT}")

MACRO(enable_stat)
  if ( WFC_ENABLE_STAT )
    foreach(arg IN ITEMS ${ARGN})
      message(STATUS "Enable statistics for ${arg}")
      target_compile_definitions(${arg} PUBLIC WFC_ENABLE_STAT=ON)
    endforeach()
  endif()
ENDMACRO(enable_stat)

MACRO(disable_stat)
  if ( WFC_ENABLE_STAT )
    foreach(arg IN ITEMS ${ARGN})
      message(STATUS "Disable statistics for ${arg}")
      target_compile_definitions(${arg} PUBLIC WFC_ENABLE_STAT=OFF)
    endforeach()
  endif()
ENDMACRO(disable_stat)
